alias chrome="google-chrome --password-store=basic & disown"
alias studio="/opt/android-studio/bin/studio.sh & disown"
alias home="cd ~"
alias spotify="/usr/share/spotify/spotify & disown"
alias android="cd ~/AndroidStudioProjects"
alias push="git push origin master"
alias pull="git pull origin master"
alias subl="/opt/sublime_text/sublime_text"
alias sublime="/opt/sublime_text/sublime_text"
alias npp="/opt/sublime_text/sublime_text"
alias update="sudo apt-get update
sudo apt-get upgrade
sudo apt autoremove"
alias matlab="/usr/local/MATLAB/R2017a/bin/matlab & disown"
alias dotfiles="cd ~/dotfiles/"
alias SDCND="cd ~/SDCND/"
alias activate_term1="source activate carnd-term1"
alias line="/opt/google/chrome/google-chrome --profile-directory=Default --app-id=menkifleemblimdogmoihpfopnplikde"
alias keep="/opt/google/chrome/google-chrome --profile-directory=Default --app-id=hmjkmjkepdijhoojdojkdfohbdgmmhki"
alias youtube="/opt/google/chrome/google-chrome --profile-directory=Default --app-id=blpcfgokakmgnkcojhhkbfbldkacnbeo"
alias TensorIntro_activate="source activate IntroToTensorFlow"
alias TensorIntro_deactivate="source deactivate IntroToTensorFlow"
alias arduino="/opt/arduino/arduino &"